version: '3'

services:
    node-app:
        build: ./cypress-tutorial-build-todo-starter
        volumes:
            - ./cypress-tutorial-build-todo-starter:/usr/src/app
        ports:
            - 3030:3030
    cypress:
        image: cypress
        build: ./cypress
        depends_on:
            - node-app
        environment:
            - CYPRESS_baseUrl=http://node-app
        command: npm run cypress:all
        volumes:
            - ./cypress-tutorial-build-todo-starter/cypress:/app/cypress
            - ./cypress-tutorial-build-todo-starter/cypress.json:/app/cypress.json