version: '3'

services:
    node-app:
        build: ./cypress-tutorial-build-todo-starter
        ports:
            - 3030:3030
    cypress:
        image: cypress/included:9.5.2
        depends_on:
            - node-app
        environment:
            - CYPRESS_baseUrl=http://node-app:3030
        volumes:
            - ./cypress-tutorial-build-todo-starter:/app
        working_dir: /app
    orchestrator:
        build: ./flask
        ports:
            - 5000:5000
        volumes:
          - .:/code
    prometheus:
        image: prom/prometheus
        ports:
          - 9090:9090
    grafana:
        image: grafana/grafana-enterprise:8.2.0
        ports:
            - 5050:5050
        depends_on:
            - prometheus

